[package]
name = "gigagei"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "*", features = ["tls"] }
xmlparser = "*"
textwrap = "*"
